### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by Bennoo** [AgoraIO-Community/Angular-Agora-RTC#7]
Hello,

Thanks for implementing this wrapper.

I cannot find how to configure the logging. For the moment the component is logging every level in the console, I would like to configure that.
Is this possible?

Thanks,

**Comment by rurico** [comment]
```typescript

constructor(private ngxAgoraService: NgxAgoraService) { }

ngOnInit() {
  this.agoraService.AgoraRTC.Logger.setLogLevel( ... );
}
```

**Comment by elmartino** [comment]
@rurico your answer is when using ngx-arora, not angular-agora-rtc 

Anyone knows how to disable logging in angular-agora-rtc ?

**Comment by rurico** [comment]
@elmartino
```typescript
import * as agoraSDK from 'agora-rtc-sdk';
class ... {
  ngOnInit() {
    agoraSDK.Logger.setLogLevel( ... );
  }
}
```

**Comment by elmartino** [comment]
Thanks @rurico ! Works like a charm!

**Comment by sobaidali** [comment]
Hi, can anyone suggest how to show logs in toasts.

**Comment by Bennoo** [comment]
Okay this is from another times. I even don't remember what the issue was. I close this
